services:
  test-database:
    image: postgres:17.4-alpine
    restart: always
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    expose:
      - 5434
    volumes:
      - test-db-data:/var/lib/postgresql/data:cached

volumes:
  test-db-data:
